# Use Node.js base image
FROM node:18.20.4

# Set working directory in container
WORKDIR /app

# Copy package.json and package-lock.json (if present)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Expose Angular dev server port
EXPOSE 4200

# Run the Angular development server
CMD ["npm", "start"]
